-- ============================================================
-- PART 4: BUSINESS QUESTIONS & QUERIES (15)
-- ============================================================

-- Q1: Average number of appointments per patient in the last 6 months
SELECT
    p.PatientID,
    p.FirstName + ' ' + p.LastName AS PatientName,
    COUNT(a.AppointmentID) AS TotalAppointments
FROM Patient p
JOIN Appointment a ON a.PatientID = p.PatientID
WHERE a.AppointmentDate >= DATEADD(MONTH, -6, GETDATE())
GROUP BY p.PatientID, p.FirstName, p.LastName
ORDER BY TotalAppointments DESC;
GO

-- Q2: Doctors with the highest patient load vs their availability
SELECT
    d.DoctorID,
    d.FirstName + ' ' + d.LastName AS DoctorName,
    d.Specialization,
    d.Availability,
    COUNT(a.AppointmentID) AS TotalAppointments
FROM Doctor d
LEFT JOIN Appointment a ON a.DoctorID = d.DoctorID
    AND a.Status = 'Completed'
GROUP BY d.DoctorID, d.FirstName, d.LastName, d.Specialization, d.Availability
ORDER BY TotalAppointments DESC;
GO

-- Q3: Total revenue generated by department in the last quarter
SELECT
    dep.DepartmentName,
    SUM(b.TotalAmount) AS TotalRevenue,
    COUNT(b.BillingID) AS BillingCount
FROM Billing b
JOIN Appointment a   ON a.PatientID    = b.PatientID
JOIN Department dep  ON dep.DepartmentID = a.DepartmentID
WHERE b.PaymentStatus = 'Paid'
  AND b.PaymentDate >= DATEADD(QUARTER, -1, GETDATE())
GROUP BY dep.DepartmentName
ORDER BY TotalRevenue DESC;
GO

-- Q4: Top 5 most prescribed medicines in the last 3 months
SELECT TOP 5
    m.MedicineName,
    m.Manufacturer,
    COUNT(p.PrescriptionID) AS TimesPrescribed
FROM Prescription p
JOIN Medicine     m  ON m.MedicineID = p.MedicineID
JOIN MedicalRecord mr ON mr.RecordID = p.RecordID
WHERE mr.VisitDate >= DATEADD(MONTH, -3, GETDATE())
GROUP BY m.MedicineName, m.Manufacturer
ORDER BY TimesPrescribed DESC;
GO

-- Q5: Room utilization percentage by room type in the last month
SELECT
    r.RoomType,
    COUNT(DISTINCT r.RoomID)            AS TotalRooms,
    COUNT(DISTINCT ra.RoomID)           AS OccupiedRooms,
    CAST(
        COUNT(DISTINCT ra.RoomID) * 100.0
        / NULLIF(COUNT(DISTINCT r.RoomID), 0)
    AS DECIMAL(5,2))                    AS OccupancyPct
FROM Room r
LEFT JOIN RoomAssignment ra ON ra.RoomID = r.RoomID
    AND ra.AdmissionDate >= DATEADD(MONTH, -1, GETDATE())
GROUP BY r.RoomType
ORDER BY OccupancyPct DESC;
GO

-- Q6: Patients who have been admitted to a room more than once
SELECT
    p.PatientID,
    p.FirstName + ' ' + p.LastName AS PatientName,
    COUNT(ra.AssignmentID)          AS Admissions,
    SUM(DATEDIFF(DAY, ra.AdmissionDate, ra.DischargeDate)) AS TotalDaysAdmitted
FROM Patient p
JOIN RoomAssignment ra ON ra.PatientID = p.PatientID
GROUP BY p.PatientID, p.FirstName, p.LastName
HAVING COUNT(ra.AssignmentID) > 1
ORDER BY Admissions DESC;
GO

-- Q7: Outstanding unpaid bills with patient contact info
SELECT
    b.BillingID,
    p.FirstName + ' ' + p.LastName AS PatientName,
    p.PhoneNumber,
    p.Email,
    b.TotalAmount,
    b.PaymentStatus
FROM Billing b
JOIN Patient p ON p.PatientID = b.PatientID
WHERE b.PaymentStatus = 'Unpaid'
ORDER BY b.TotalAmount DESC;
GO

-- Q8: Most common diagnoses across all medical records
SELECT
    mr.Diagnosis,
    COUNT(*) AS DiagnosisCount
FROM MedicalRecord mr
GROUP BY mr.Diagnosis
ORDER BY DiagnosisCount DESC;
GO

-- Q9: Number of appointments per department per month in 2024
SELECT
    dep.DepartmentName,
    MONTH(a.AppointmentDate)  AS [Month],
    COUNT(a.AppointmentID)    AS AppointmentCount
FROM Appointment a
JOIN Department dep ON dep.DepartmentID = a.DepartmentID
WHERE YEAR(a.AppointmentDate) = 2024
GROUP BY dep.DepartmentName, MONTH(a.AppointmentDate)
ORDER BY dep.DepartmentName, [Month];
GO

-- Q10: Doctors who have not had any appointments in the last 90 days
SELECT
    d.DoctorID,
    d.FirstName + ' ' + d.LastName AS DoctorName,
    d.Specialization,
    dep.DepartmentName
FROM Doctor d
JOIN Department dep ON dep.DepartmentID = d.DepartmentID
WHERE d.DoctorID NOT IN (
    SELECT DISTINCT DoctorID FROM Appointment
    WHERE AppointmentDate >= DATEADD(DAY, -90, GETDATE())
)
ORDER BY dep.DepartmentName;
GO

-- Q11: Average bill amount by payment method
SELECT
    PaymentMethod,
    COUNT(*)                         AS Transactions,
    CAST(AVG(TotalAmount) AS DECIMAL(10,2)) AS AvgBillAmount,
    CAST(SUM(TotalAmount) AS DECIMAL(10,2)) AS TotalRevenue
FROM Billing
WHERE PaymentStatus = 'Paid'
GROUP BY PaymentMethod
ORDER BY TotalRevenue DESC;
GO

-- Q12: Staff distribution by role and department
SELECT
    dep.DepartmentName,
    s.Role,
    COUNT(s.StaffID) AS StaffCount
FROM Staff s
JOIN Department dep ON dep.DepartmentID = s.DepartmentID
GROUP BY dep.DepartmentName, s.Role
ORDER BY dep.DepartmentName, StaffCount DESC;
GO

-- Q13: Patients with both appointments and room admissions
--      (identifies hospitalized patients)
SELECT
    p.PatientID,
    p.FirstName + ' ' + p.LastName AS PatientName,
    p.Gender,
    COUNT(DISTINCT a.AppointmentID)  AS Appointments,
    COUNT(DISTINCT ra.AssignmentID)  AS RoomStays
FROM Patient p
JOIN Appointment    a  ON a.PatientID  = p.PatientID
JOIN RoomAssignment ra ON ra.PatientID = p.PatientID
GROUP BY p.PatientID, p.FirstName, p.LastName, p.Gender
ORDER BY RoomStays DESC, Appointments DESC;
GO

-- Q14: Medicine stock value and low-stock alert (under 100 units)
SELECT
    MedicineID,
    MedicineName,
    Manufacturer,
    StockQuantity,
    Price,
    CAST(StockQuantity * Price AS DECIMAL(12,2)) AS StockValue,
    CASE WHEN StockQuantity < 100 THEN 'LOW STOCK' ELSE 'OK' END AS StockAlert
FROM Medicine
ORDER BY StockQuantity ASC;
GO

-- Q15: Full patient summary — appointments, records, billing, room stays
SELECT
    p.PatientID,
    p.FirstName + ' ' + p.LastName          AS PatientName,
    p.DateOfBirth,
    DATEDIFF(YEAR, p.DateOfBirth, GETDATE()) AS Age,
    p.Gender,
    COUNT(DISTINCT a.AppointmentID)          AS TotalAppointments,
    COUNT(DISTINCT mr.RecordID)              AS MedicalRecords,
    COUNT(DISTINCT ra.AssignmentID)          AS RoomAdmissions,
    ISNULL(SUM(b.TotalAmount), 0)            AS TotalBilled,
    ISNULL(SUM(CASE WHEN b.PaymentStatus='Paid' THEN b.TotalAmount END), 0) AS TotalPaid
FROM Patient p
LEFT JOIN Appointment    a  ON a.PatientID  = p.PatientID
LEFT JOIN MedicalRecord  mr ON mr.PatientID = p.PatientID
LEFT JOIN RoomAssignment ra ON ra.PatientID = p.PatientID
LEFT JOIN Billing        b  ON b.PatientID  = p.PatientID
GROUP BY p.PatientID, p.FirstName, p.LastName, p.DateOfBirth, p.Gender
ORDER BY TotalBilled DESC;
GO